toram/toram/chatapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='chatapp'
urlpatterns=[
    path(r'', views.index, name='index'),
    path(r'mychatroom',views.my_chat_room, name='my_chat_room'),
    path(r'setting', views.setting, name='setting'),
    path(r'chat/<id>',views.chat,name='chat_room'),
    path(r'chat/<id>/<messageid>',views.inchat,name='in_chat_room'),    
    path(r'chat/<id>/3/detail',views.detail, name='detail'),
    path(r'chat/<id>/2/summary',views.summary,name='summary'),
    path(r'chat/newroom/',views.newroom,name="newroom"),
    path(r'chat/<id>/media/images',views.images,name="images")

] 

toram/toram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from chatapp import views as cahtapp_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(r'HmrrCAMfG_W7/ePR5yuTcRhLR/admin/', admin.site.urls),
    path(r'', include('chatapp.urls')),
    path(r'account/', include('account.url')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

toram/toram/account/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def _create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('名前を入力してください')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(password, **extra_fields)

    def create_superuser(self, username, password, email=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('is_staff=Trueである必要があります。')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('is_superuser=Trueである必要があります。')
        return self._create_user(username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.CharField(verbose_name='username', max_length=30, unique=True,)
    icon = models.ImageField(verbose_name='プロフィール画像', upload_to="icon/", blank=True, null=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    is_staff = models.BooleanField(_("staff status"), default=False)
    is_active = models.BooleanField(_("active"), default=True)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(_("email_address"), unique=True, null=True, blank=True)

    objects = UserManager()
    USERNAME_FIELD="username"


    def __str__(self):
        return self.username

    def clean(self):
        super().clean()

toram/toram/chatapp/models.py
from doctest import master
from django.db import models
from django.utils import timezone
import uuid
from account.models import User


# Create your models here.
# def images_directory_path(instance, filename):
#     return 'image-{0}/{1}'.format(instance.id, filename)

class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    image=models.ImageField(upload_to='media/' ,null=True, blank=True)
    detail=models.TextField(max_length=400, null=True, blank=True)
    master=models.ForeignKey(
        User,
        related_name='room_master',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Messages(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    msg = models.TextField(null=True, blank=True)
    room = models.ForeignKey(
        Room,
        related_name='room_mesages',
        on_delete=models.CASCADE
    )
    # username = models.CharField(max_length=50)
    username=models.ForeignKey(
        User,
        related_name='pmsg_user',
        on_delete=models.CASCADE,

    )
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.msg

class PMaltipleImages(models.Model):
    image=models.ImageField(upload_to='media/', null=True, blank=True)
    message=models.ForeignKey(
        Messages, 
        verbose_name="pimages",  
        on_delete=models.CASCADE
        )
    room = models.ForeignKey(
        Room,
        related_name='proom',
        on_delete=models.CASCADE
    )



class InMessages(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    msg = models.TextField(null=True, blank=True)
    pmsg = models.ForeignKey(
        Messages,
        related_name='in_mesages',
        on_delete=models.CASCADE
    )
    # username = models.CharField(max_length=50)
    username=models.ForeignKey(
        User,
        related_name='smsg_user',
        on_delete=models.CASCADE,

    )
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.msg


class SMaltipleImages(models.Model):
    image=models.ImageField(upload_to='media/', null=True, blank=True)
    message=models.ForeignKey(
        InMessages, 
        verbose_name="simages",  
        on_delete=models.CASCADE
        )


class FollowRoom(models.Model):
    user=models.ForeignKey(
        User,
        related_name='user_follow_room',
        on_delete=models.CASCADE
    )
    room=models.ForeignKey(
        Room,
        related_name='followed_room_by_user',
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return "{} : {}".format(self.room.name, self.user.username)

class Summary(models.Model):
    primarymessage=models.ForeignKey(
        Messages,
        related_name='primary',
        on_delete=models.CASCADE,
        null=True, 
        blank=True
    )
    secondarymessage=models.ForeignKey(
        InMessages,
        related_name='secondary',
        on_delete=models.CASCADE,
        null=True, 
        blank=True
    )
    room=models.ForeignKey(
        Room,
        related_name='room',
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return "{}".format(self.room.name)



toram/toram/chatapp/views.py
from django.shortcuts import render, redirect, get_list_or_404
from pymysql import NULL
from account.views import change
import chatapp, account
import os
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from chatapp.form import *
from account.form import UserChangeForm
from .models import *
from account.views import *
from django.template import loader
from django.urls import path, include
from account.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_POST
from django.db.models import Q
from itertools import chain


# Create your views here.

def index(request):
    results=Room.objects.none()
    wresults=[]
    pchat=Messages.objects.none()
    schat=InMessages.objects.none()
    text=""
    ctext=""
    if request.method=='POST':
        if "search" in request.POST:
            print('bad')
            query=request.POST.get('search-room')
            query=query.split()
            for word in query:
                results = results.union(Room.objects.filter(Q(name__icontains=word)|Q(detail__icontains=word)).all())        
            if results.exists()==False:
                text="見つかりません"
            else:
                pass


        elif "search_word_button" in request.POST:
            query=request.POST.get('search_word')
            query=query.split()
            for word in query:
                pchat = pchat.union(Messages.objects.filter(Q(msg__icontains=word)).all())   
                schat = schat.union(InMessages.objects.filter(Q(msg__icontains=word)).all())
            if pchat.exists()==False and schat.exists==False:
                ctext="見つかりません"
            else:
                pass

    
    context = {
    'list':Room.objects.all().order_by('-created_at') ,
    'results':results,
    'text':text,
    'ctext':ctext,
    'pchat':pchat,
    'schat':schat,

    }
    return render(request, '../templates/chatapp/index.html',context)


@login_required
def newroom(request):
    form = RoomCreateForm()
    name=request.POST.get('name')
    if request.POST:
        form=RoomCreateForm(request.POST or None, request.FILES)

    context = {
        'list':Room.objects.all().order_by('-created_at') ,
        'form':form
    }
    if request.method == 'POST' and form.is_valid():
        if Room.objects.filter(name=name).exists()==False:
            result=Room.objects.create(name=request.POST.get('name'),image=request.FILES.get('image'), master=User.objects.get(username=request.user.username), detail="")
            id=Room.objects.get(name=name).id
            room = Room.objects.filter(name=Room.objects.get(id=id))[0]
            follow_view(request,name=room.name)
            return HttpResponseRedirect(reverse('chatapp:chat_room',args=[id]))
        else:
            context['text']='同名の部屋があります。別の名前で作成してください'
            return render(request, '../templates/chatapp/newroom.html',context)

    else:
        form = RoomCreateForm()
    return render(request, '../templates/chatapp/newroom.html',context)

@login_required
def my_chat_room(request):
    username=User.objects.get(username=request.user.username)
    rooms=FollowRoom.objects.filter(user=username).order_by('-created_at')
    context={
        'rooms':rooms,
    }
    return render(request, '../templates/chatapp/my_chat_room.html',context)

def setting(request):
    judgeprofileedit=False
    form=UserChangeForm()
    context={"judgeprofileedit":judgeprofileedit,}
    if request.method=='POST':
        if "changeprofile" in request.POST:
           context=change(request)
        if "userdelete" in request.POST:
            User.objects.filter(username=request.user.username).delete()
            logout(request)
            return index(request)
        if "profileedit" in request.POST:
            judgeprofileedit=True
            context={'form':form,
                     'judgeprofileedit':judgeprofileedit,
                    }
    template=loader.get_template('chatapp/setting.html')

    return HttpResponse(template.render(context, request))

# チャットview
def chat(request, id):
    arrow=False
    room_name=Room.objects.get(id=id)
    if request.user.is_authenticated:
        username=User.objects.get(username=request.user)
    else:
        username=User.objects.none()
    messageform = ChatForm(request.POST or None)
    message=request.POST.get('msg')
    images=request.FILES.getlist('images')
    room = Room.objects.filter(name=room_name)[0]
    messages = Messages.objects.filter(room__name=room_name).order_by('-created_at') 
    template = '../templates/chatapp/chat_room.html'
    loadtemplate=loader.get_template('chatapp/chat_room.html')
    

    if request.method == 'POST':
        #チャットバリテーションと登録        
        if message!=None and "sendchat" in request.POST and message!="":
            result=Messages.objects.create(username=username, msg=message, room=room)
            for l in images:
                imagesobject=PMaltipleImages.objects.create(image=l, message=result, room=room)

            messages = Messages.objects.filter(room__name=room_name).order_by('-created_at')
            messageform=ChatForm()
            roomid=str(room.id)
            return redirect('chatapp:chat_room',roomid)
        #マイルーム追加と解除
        elif "follow" in request.POST:
            follow_view(request,name=room.name)
        elif "unfollow" in request.POST:
            try:
                unfollow_view(request,name=room.name)
            except:
                pass
        elif "msg_del" in request.POST:
            delmsg=Messages.objects.filter(id=request.POST.get('hidden_msg_del'))
            delmsg.delete()

    if request.user.is_authenticated:
        follow=FollowRoom.objects.filter(user=username,room=room).exists()
    else:
        follow=False
    context = {
        'msg':messages,
        'room': room,
        'messageform':messageform,
        'follow': follow,
        'arrow':arrow,
    }
    return render(request,template,context)

# チャットinチャット
def inchat(request, id, messageid):
    displaysummary=False
    room=Room.objects.get(id=id)
    primarymessage=Messages.objects.get(id=messageid)
    summarytext=""
    already="登録済み"
    template = loader.get_template('chatapp/in_chat.html')
    if request.user.is_authenticated:
        username=User.objects.get(username=request.user)
    else:
        username=User.objects.none()
    messageform = ChatForm(request.POST or None, request.FILES)
    message=request.POST.get('msg')
    images=request.FILES.getlist('images')
    messages = InMessages.objects.filter(pmsg=primarymessage).order_by('-created_at') 
   
    if request.method == 'POST':
        if message!=None and "sendchat" in request.POST and message!="":
            result=InMessages.objects.create(username=username, msg=message, pmsg=primarymessage)
            for l in images:
                imagesobject=SMaltipleImages.objects.create(image=l, message=result)

            messages = InMessages.objects.filter(pmsg=primarymessage).order_by('-created_at')
            messageform=ChatForm()
            return redirect('chatapp:in_chat_room',id,str(primarymessage.id),)

        elif "psummary" in request.POST and summarytext != already:
            messageobject=Messages.objects.get(id=request.POST.get('objectid'))
            register_summary(request, room, messageobject)

        elif "ssummary" in request.POST and summarytext != already:
            messageobject=InMessages.objects.get(id=request.POST.get('objectid'))
            register_summary(request, room, messageobject)

        elif "add-summary" in request.POST:
            displaysummary=True

        elif "smsg_del" in request.POST:
            delmsg=InMessages.objects.filter(id=request.POST.get('hidden_msg_del'))
            delmsg.delete()


    context = {
        'room':room,
        'primarymessage':primarymessage,
        'msg':messages,
        'messageform':messageform,
        'displaysummary':displaysummary
    }
    return HttpResponse(template.render(context,request))

def images(request,id):
    if Messages.objects.filter(id=id).exists():
        pmobj=Messages.objects.get(id=id)
        images=pmobj.pmaltipleimages_set.all()
    elif InMessages.objects.filter(id=id).exists():
        smobj=InMessages.objects.get(id=id)
        images=smobj.smaltipleimages_set.all()

    context={'images':images,}
    return render(request,"chatapp/images.html",context)

def detail(request,id):
    all_user_display=True
    room_name=Room.objects.get(id=id)
    form=ChangeRoomFieldsFrom()
    room = Room.objects.filter(name=room_name)[0]
    field=Room.objects.get(name=room_name)
    roomid=field.id
    name=request.POST.get('name')
    context={}
    text=""
    template = loader.get_template('chatapp/detail.html')
    judge=str(request.user.username)==str(field.master)
    if request.POST:
        form=ChangeRoomFieldsFrom(request.POST, request.FILES)

    if request.method == 'POST':
        if "change" in request.POST :
            if form.is_valid():
                if Room.objects.filter(name=name).exists()==False or field.id==Room.objects.get(name=name).id:
                    field.name=form.cleaned_data['name']
                    if request.POST.get('image')!="":
                        field.image=form.cleaned_data['image']
                    field.detail=form.cleaned_data['detail']
                    field.save()
                    room = Room.objects.filter(name=field.name)[0]

            else:
                text='同名の部屋があります。別の名前で作成してください'
                room.image=request.FILES.get('image')#機能していない

toram/toram/templates/chatapp/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}chat room detail{% endblock %}
{% block content %}
<h1>ルーム詳細</h1>
<main>
    <nav class="chatindex">
        <ul>
            <li class="chatindex">
                <a href="/chat/{{ room.id }}">チャット</a>
            </li>
            <li class="chatindex">
                <a href="/chat/{{room.id}}/2/summary" >まとめ</a>
            </li>        
            <li class="chatindex">
                <a href="/chat/{{room.id}}/3/detail">ルーム情報</a>
            </li>
        </ul>
    </nav>
    <div class="room_detail">
    {%if all_user_display%}
    <div class="display">
        <p>部屋の名前：{{field.name}}</p>
        {%if field.image == ""%}
        <p><img src="{% static "img/no_image.png"%}" with="150" height="150"></p>
        {%else%}
        <p>画像：<img src="/media/{{field.image}}" with="150" height="150"></p>
        {%endif%}
        <p>ルームマスター：{{field.master}}</p>
        <p>詳細：{{field.detail | linebreaksbr }}</p>
    </div>
    {%endif%}
    {%if judge%}
    <form action={% url 'chatapp:detail' room.id%} method="POST">
        {% csrf_token %}
        <div class="edit-detail">
            <button class="send" type="submit" name="edit" >
            編集
            </button>
        </div>
    </form>
    {%endif%}

        {%if edit%}
        <div class="change-room-fields-box">
            <form action={% url 'chatapp:detail' room.id%} method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <label for="id_name">部屋の名前:</label>
                    <input value="{{room.name}}" type="text" name="name" maxlength="50" required id="id_name">      
                </p>
                <p>{{text}}</p>
                <p>
                    <label for="id_image">アイコン画像:</label>
                    <input type="file" name="image" accept="image/*" id="id_image">
                </p>
                <p>
                    <label for="id_detail">ルーム詳細:</label>
                    <textarea name="detail" cols="40" rows="10" maxlength="400" id="id_detail">{{room.detail}}</textarea>
                </p>   
                <p><input type="submit" class="send" name="change" value="送信"> </p>    
            </form>
        </div>
        <br>
        <form action={% url 'chatapp:detail' room.id%} method="POST">
            {% csrf_token %}
            <div class="clean-room">
                <button class="send" type="submit" name="roomdelete" onclick='return confirm("本当に削除しますか？");'>
                ルームを削除
                </button>
            </div>
        </form>
    {%endif%}
    </div>
</main>
</div>
{% endblock %}

toram/toram/templates/chatapp/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
{% comment %} <div class="container"> {% endcomment %}
<h1>HOME</h1>
<main>

    <div class="create-room">
        {%if user.is_authenticated%}
        <a href="{% url 'chatapp:newroom'%}" class="btn btn--orange btn-c"><i class="fa far fa-envelope"></i>ルーム作成</a>
        {%else%}
        <p>ログインすると部屋が作成できます</p>
        {%endif%}
        <br>
    </div>

    <h2>ルーム検索</h2>
    <div class="room-search-detail">
        <p class="search-discription">
            ルーム名、ルーム詳細より検索します
        </p>
    </div>
    <div class="search-room">
        <form action={% url 'chatapp:index'%} method="POST">
                <div class="input-group">
                    {% csrf_token %}
                    <input class="form-control form-control-lg" name="search-room" placeholder="ルーム検索">
                    <button type="submit" class="btn btn-primary" name="search">検索</button>
                </div>
            </form> 
        
            {%for result in results%}
            <div class="kakomi">
                <div class="center">
                {%if result.image == ''%}
                <p><a href="/chat/{{ result.id }}"><img src="static/img/no_image.png"width="150" height="150" border=""></a></p>
                {%else%}
                <p><a href="/chat/{{ result.id }}"><img src="media/{{result.image}}"width="150" height="150" border="0" ></a></p>
                {%endif%}
                <p><a href="/chat/{{ result.id }}">{{result.name}}</a></p>
            </div>    
        </div> 
            {%endfor%}        
            <br>


        
    </div>

    <h2>チャット検索</h2>
    <div class="chat-search-detail">
        <p class="search-discription">
            キーワードからチャットを検索します
        </p>
    </div>
    <div class="search-room">
        <form action={% url 'chatapp:index'%} method="POST">
                <div class="input-group">
                    {% csrf_token %}
                    <input class="form-control form-control-lg" name="search_word" placeholder="ワード検索">
                    <button type="submit" class="btn btn-primary" name="search_word_button">検索</button>
                </div>
            </form> 
            
        
            {%for p in pchat%}
            <div class="kakomi">
                <div class="search-primarymsg">
                <p>{{p.msg}}</p>

                {%for img in p.pmaltipleimages_set.all%}
                {% if forloop.counter <= 1 %}
                    <p id="image">
                        <a href="/chat/{{ p.room.id }}/{{p.id}}"><img src="/media/{{img.image}}" class="imagefield"></a>
                        {{p.pmaltipleimages_set.all.count}}枚の画像
                    </p>
                {%endif%}
            {%endfor%}

                <p><a href="/chat/{{ p.room.id }}/{{p.id}}">このチャットへ移動</a>
            </div>    
        </div> 
            {%endfor%}
            {%for s in schat%}
            <div class="kakomi">
                <div class="search-secondarymsg">
                <p>{{s.msg}}</p>
                
                {%for img in s.smaltipleimages_set.all%}
                {% if forloop.counter <= 1 %}
                    <p id="image">
                        <a href="/chat/{{ s.pmsg.room.id }}/{{s.pmsg.id}}"><img src="/media/{{img.image}}" with="150" height="150"></a>
                        {{s.smaltipleimages_set.all.count}}枚の画像
                    </p>
            {%endif%}
            {% endfor %}

                <p><a href="/chat/{{ s.pmsg.room.id }}/{{s.pmsg.id}}">このチャットへ移動</a>
            </div>    
        </div> 
            {%endfor%}          
            <br>


    <div class="new-room-list">
        <h2>新作ルーム</h2>
        <div class="select-room-box">
            {%for lis in list%}
            {% if forloop.counter <= 6 %}
            <div class="kakomi">
                <div class="center">
                {%if lis.image == ''%}
                <p><a href="/chat/{{ lis.id }}"><img src="static/img/no_image.png"width="150" height="150" border=""></a></p>
                {%else%}
                <p><a href="/chat/{{ lis.id }}"><img src="media/{{lis.image}}"width="150" height="150" border="0" ></a></p>
                {%endif%}
                <p><a href="/chat/{{ lis.id }}">{{lis.name}}</a></p>
            </div>    
        </div> 
            {%endif%}   
            {%endfor%}
    </div>
    </div>

</main>
</div>
{% endblock %}



toram/toram/templates/chatapp/my_chat_room.html
{% extends 'base.html' %}
{% load static %}
{% block title %}my_chat_room{% endblock %}
{% block content %}
<h1>追加したマイルーム</h1>
<main>
    {%for room in rooms%}
    <div class="kakomi">
        <div class="center">
            
            {%if room.room.image%}
            <p><a href={% url 'chatapp:chat_room' room.room.id %}><img src="/media/{{room.room.image}}" width="150" height="150"></a></p>
            {%else%}
            <p><a href={% url 'chatapp:chat_room' room.room.id %}><img src="static/img/no_image.png" width="150" height="150"></a></p>
            {%endif%}
            <p><a href={% url 'chatapp:chat_room' room.room.id %}>{{room.room.name}}</a></p>

        </div>
    </div>
        {%endfor%}
</main>
</div>
{% endblock %}

toram/toram/templates/chatapp/newroom.html
{% extends 'base.html' %}
{% load static %}
{% block title %}create room{% endblock %}
{% block content %}
<h1>ルーム作成</h1>
<main>
    <div class="create-room-box">
        <form action={% url 'chatapp:newroom'%} method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}  
            <input type="submit" class="send" name="button" value="作成"> 
        </form>
    </div>
    <p>{{text}}</p>
</main>
</div>
{% endblock %}

toram/toram/templates/chatapp/setting.html
{% extends 'base.html' %}
{% load static %}
{% block title %}setting{% endblock %}
{% block content %}
<h1>設定</h1>
<main>
    {%if judgeprofileedit%}
    <div class="profile_body profile-change">
    {%if username_already_exists != None%}
    {{username_already_exists}}
    {%endif%}
    <div class="back">
    <a href={% url 'chatapp:setting'%} >戻る</a>
    </div>
    <form action={% url 'chatapp:setting'%} method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
        <label for="id_username">ユーザー名:</label>
        <input type="text" name="username" maxlength="30" value={{user.username}}>
        </p>  
        <p>
            <label for="id_icon">プロフィール画像:</label>
            <input type="file" name="icon" accept="image/*" id="id_icon">            
        </p>
        <p><input type="submit" class="send" name="changeprofile" value="送信"> </p>    
      </form>
    <br>

    <br>
    <form action={% url 'chatapp:setting'%} method="POST">
        {% csrf_token %}
        <div class="userdelete">
            <button class="send" type="submit" name="userdelete" onclick='return confirm("本当に削除しますか？");'>
            アカウントを削除
            </button>
        </div>
    </form>
    <br> 
</div>
    {%else%}
        <div class="profile">
            {%if user.is_authenticated%}
            <h2>ユーザー情報表示</h2>
            <div class="profile_body">
            <p>ユーザー名：{{user.username}}</p>
            {% if user.icon %}
                <img src="/media/{{user.icon}}" width="150" height="150" border="">
            {% else %}
                <img src="static/img/no_image.png" width="150" height="150" border="">
            {% endif %}
            <br>
            {%endif%}
        
        <div>
            {%if user.is_authenticated%}
            <form action={% url 'chatapp:setting'%} method="POST">
                {% csrf_token %}
                <p><input type="submit" class="send" name="profileedit" value="プロフィールを編集"></p>    
            </fomr>
        </div>
            {%endif%}
        </div>
    </div>
    {%endif%}

    <h2>問い合わせフォーム</h2>
    <div class="contact">
        <p><a href="#">toram.chat@gmail.com</a></p>
        <p><a href="https://twitter.com/ToramChat">Twitter</a></p>
    </div>
</main>
{% endblock %}

toram/toram/templates/chatapp/summary.html
{% extends 'base.html' %}
{% load static %}
{% block title %}summary{% endblock %}
{% block content %}
<h1>まとめ</h1>
<main>
    <nav class="chatindex">
        <ul>
            <li class="chatindex">
                <a href="/chat/{{ room.id }}">チャット</a>
            </li>
            <li class="chatindex">
                <a href="/chat/{{room.id}}/2/summary" >まとめ</a>
            </li>        
            <li class="chatindex">
                <a href="/chat/{{room.id}}/3/detail">ルーム情報</a>
            </li>
        </ul>
    </nav>
    
    <div class="summary">
        {%for lis in summary%}
        <div class="summary-message">
            {%if lis.primarymessage%}
            <div class="kakomi-maru4"><span class="title-maru4">{{lis.primarymessage.username}}</span>

                {%if user == room.master%}
                <form action={% url 'chatapp:summary' room.id%} method="POST">
                    {% csrf_token %}
                    <div class="clean-summary">
                        <input type="hidden" name="summaryobjectid" value={{lis.primarymessage.id}}>
                        <button class="send" type="submit" name="summarydelete" onclick='return confirm("本当に削除しますか？");'>まとめから削除</button>
                    </div>
                </form>
                <br>
                {%endif%}

                <p>{{lis.primarymessage.msg}}</p>
                {%for img in lis.primarymessage.pmaltipleimages_set.all%}
                    {% if forloop.counter <= 1 %}
                        <p id="image">
                            <a href="/chat/{{lis.primarymessage.id}}/media/images" target="_blank"><img src="/media/{{img.image}}" with="150" height="150"></a>
                            {{lis.primarymessage.pmaltipleimages_set.all.count}}枚の画像
                        </p>
                    {%endif%}
                {%endfor%}

                <a href="/chat/{{lis.primarymessage.room.id}}/{{lis.primarymessage.id}}">
                    <p>チャットの詳細</p>
                </a>


            </div>
        </div>

            {%elif lis.secondarymessage%}
            <div class="skakomi-maru4"><span class="stitle-maru4">{{lis.secondarymessage.username}}</span>

                {%if user == room.master%}
                <form action={% url 'chatapp:summary' room.id%} method="POST">
                    {% csrf_token %}
                    <div class="clean-summary">
                        <input type="hidden" name="summaryobjectid" value={{lis.secondarymessage.id}}>  
                        <button class="send" type="submit" name="summarydelete" onclick='return confirm("本当に削除しますか？");'>まとめから削除</button>
                    </div>
                </form>
                <br>
                {%endif%}

                <p>{{lis.secondarymessage.msg}}</p>

                {%for img in lis.secondarymessage.smaltipleimages_set.all%}
                    {% if forloop.counter <= 1 %}
                        <p id="image">
                            <a href="/chat/{{lis.secondarymessage.id}}/media/images" target="_blank"><img src="/media/{{img.image}}" with="150" height="150"></a>
                            {{lis.secondarymessage.smaltipleimages_set.all.count}}枚の画像
                        </p>
                    {%endif%}
                {%endfor%}

                <a href="/chat/{{lis.secondarymessage.pmsg.room.id}}/{{lis.secondarymessage.pmsg.id}}">
                    <p>チャットの詳細</p>
                </a>
                

            {%endif%}
            </div>
        {%endfor%}
    </div>

    
</main>
{% endblock %}