toram/toram/chatapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='chatapp'
urlpatterns=[
    path(r'', views.index, name='index'),
    path(r'mychatroom',views.my_chat_room, name='my_chat_room'),
    path(r'setting', views.setting, name='setting'),
    path(r'chat/<id>',views.chat,name='chat_room'),
    path(r'chat/<id>/<messageid>',views.inchat,name='in_chat_room'),    
    path(r'chat/<id>/3/detail',views.detail, name='detail'),
    path(r'chat/<id>/2/summary',views.summary,name='summary'),
    path(r'chat/newroom/',views.newroom,name="newroom"),
    path(r'chat/<id>/media/images',views.images,name="images")

] 

toram/toram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from chatapp import views as cahtapp_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(r'HmrrCAMfG_W7/ePR5yuTcRhLR/admin/', admin.site.urls),
    path(r'', include('chatapp.urls')),
    path(r'account/', include('account.url')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

toram/toram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Required meta tags -->
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% endcomment %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="/docs/5.0/assets/css/docs.css" rel="stylesheet">
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/docs/5.0/assets/css/docs.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
 <!--jQuery-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>     
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.0.min.js"></script>
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %} chat</title>
      
  <!--Ad-->
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1259593776810741"
     crossorigin="anonymous"></script>
  </head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-B8KN8ZFSYC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-B8KN8ZFSYC');
</script>

<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <p><img src="{% static 'img/logo.jpg' %}" width="50" height="50" name="button_logo"></p>
          <p><a class="navbar-brand" href={%url 'chatapp:index'%} id="brand">Chat</a></p>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'chatapp:index' %}">ホーム</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'chatapp:my_chat_room' %}">マイルーム</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chatapp:setting' %}">マイページ</a>
              </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">ログイン</a>
              </li>
              <li class="nav-item">
                <a class="nav-link"  href="{% url 'account:register' %}">ユーザー登録</a>
              </li>
              {% endif %}
              {% if user.is_authenticated%}
              <li class="nav-item"  >
                <a class="nav-link" href="{% url 'chatapp:setting' %}">{{user.username}}</a>
              </li>
              {% endif %}                
            </ul>
          </div>
        </div>
      </nav>

    </heder>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
    <script src="/docs/5.0/assets/js/docs.min.js"></script>
</body>
</html>